title: Nepal Network Operators' Group (npNOG)
email: info@npnog.org.np
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Nepal Network Operators’ Group (npNOG). npNOG is a community of network operators who work in ISPs, Content Providers, Telcos and other areas of the Internet and ICT industry in Nepal.
  नेपाल नेटवर्क अपरेटर्स ग्रुपमा यहाँलाई स्वागत छ। यो इन्टरनेट सेवा प्रदायक र सूचना संचार प्रविधिको क्षेत्रमा कार्यरत व्यक्ति एवंम संस्थाहरुको समूह हो। यसको उदेश्य नेपालको इन्टर्नेट समुदायबिच समन्वय र सहकार्य बृद्दि गर्ने भुमिका खेल्नु हो।
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
theme: jekyll-theme-cayman

